{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mvinje\u001b[0m (\u001b[33mavogadro\u001b[0m). Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.13.5"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>/Users/hjalmarvinje/Documents/LSTM for option pricing/wandb/run-20221108_153245-3gcemh5f</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href=\"https://wandb.ai/avogadro/LSTM%20option%20pricing/runs/3gcemh5f\" target=\"_blank\">bright-butterfly-46</a></strong> to <a href=\"https://wandb.ai/avogadro/LSTM%20option%20pricing\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://wandb.me/run\" target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<button onClick=\"this.nextSibling.style.display='block';this.style.display='none';\">Display W&B run</button><iframe src=\"https://wandb.ai/avogadro/LSTM%20option%20pricing/runs/3gcemh5f?jupyter=true\" style=\"border:none;width:100%;height:420px;display:none;\"></iframe>"
      ],
      "text/plain": [
       "<wandb.sdk.wandb_run.Run at 0x7faefd03baf0>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from preprocessing import get_model_dataset, create_train_test, min_max_scale, df_to_xy\n",
    "from trainer import trainer\n",
    "from lstm import create_model\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Hyperparameter tuning\n",
    "import wandb\n",
    "from wandb.keras import WandbCallback\n",
    "wandb.init(project=\"LSTM option pricing\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#â€ƒCapture a dictionary of hyperparameters with config\n",
    "wandb.config = {\n",
    "  \"lr\": 0.001,\n",
    "  \"n_epochs\": 100,\n",
    "  \"n_batch\": 128\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        Quote_date Expire_date  Underlying_last   Strike  Moneyness    Ask  \\\n",
      "725110  2022-05-09  2022-05-10          3993.26   3100.0   1.288148  893.3   \n",
      "725111  2022-05-09  2022-05-10          3993.26   3200.0   1.247894  792.9   \n",
      "725112  2022-05-09  2022-05-10          3993.26   3300.0   1.210079  692.2   \n",
      "725113  2022-05-09  2022-05-10          3993.26   3400.0   1.174488  592.2   \n",
      "725114  2022-05-09  2022-05-10          3993.26   3500.0   1.140931  493.0   \n",
      "...            ...         ...              ...      ...        ...    ...   \n",
      "1533707 2022-09-30  2026-12-18          3589.70   8800.0   0.407920   31.4   \n",
      "1533708 2022-09-30  2026-12-18          3589.70   9000.0   0.398856   29.5   \n",
      "1533709 2022-09-30  2026-12-18          3589.70   9200.0   0.390185   16.2   \n",
      "1533710 2022-09-30  2026-12-18          3589.70   9600.0   0.373927   24.5   \n",
      "1533711 2022-09-30  2026-12-18          3589.70  10000.0   0.358970   21.8   \n",
      "\n",
      "           Bid   Ttl  Volatility     R  \n",
      "725110   886.3     1    0.233070  0.92  \n",
      "725111   785.4     1    0.233070  0.92  \n",
      "725112   685.8     1    0.233070  0.92  \n",
      "725113   585.4     1    0.233070  0.92  \n",
      "725114   485.9     1    0.233070  0.92  \n",
      "...        ...   ...         ...   ...  \n",
      "1533707   10.0  1540    0.234276  3.33  \n",
      "1533708    6.1  1540    0.234276  3.33  \n",
      "1533709   11.2  1540    0.234276  3.33  \n",
      "1533710    3.3  1540    0.234276  3.33  \n",
      "1533711    7.3  1540    0.234276  3.33  \n",
      "\n",
      "[776381 rows x 10 columns]\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 776381 entries, 725110 to 1533711\n",
      "Data columns (total 10 columns):\n",
      " #   Column           Non-Null Count   Dtype         \n",
      "---  ------           --------------   -----         \n",
      " 0   Quote_date       776381 non-null  datetime64[ns]\n",
      " 1   Expire_date      776381 non-null  datetime64[ns]\n",
      " 2   Underlying_last  776381 non-null  float64       \n",
      " 3   Strike           776381 non-null  float64       \n",
      " 4   Moneyness        776381 non-null  float64       \n",
      " 5   Ask              776381 non-null  float64       \n",
      " 6   Bid              776381 non-null  float64       \n",
      " 7   Ttl              776381 non-null  int64         \n",
      " 8   Volatility       776381 non-null  float64       \n",
      " 9   R                776381 non-null  float64       \n",
      "dtypes: datetime64[ns](2), float64(7), int64(1)\n",
      "memory usage: 65.2 MB\n"
     ]
    }
   ],
   "source": [
    "path_opt = \"./data/options/\"\n",
    "filenames_opt = [\"spx_eod_\" + str(year) + (str(month) if month >= 10 else \"0\"+str(month)) + \".txt\" for year in range(2022, 2022) for month in range(1, 13)] + [\"spx_eod_2022\" + (str(month) if month >= 10 else \"0\" + str(month)) + \".txt\" for month in range(1, 10)]\n",
    "path_r = \"./data/rates/\"\n",
    "filenames_r = [\"yield-curve-rates-2022.csv\", \"yield-curve-rates-1990-2021.csv\"]\n",
    "\n",
    "df_read = get_model_dataset(path_opt, filenames_opt, path_r, filenames_r, True)\n",
    "print(df_read)\n",
    "df_read.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train_x shape: (519593, 5, 4), train_y shape: (519593, 2)\n",
      "Test_x shape: (121672, 5, 4), test_y shape: (121672, 2)\n"
     ]
    }
   ],
   "source": [
    "features = [\"Moneyness\", \"Ttl\", \"R\", \"Volatility\"]\n",
    "seq_length = 5\n",
    "num_features = 4\n",
    "\n",
    "df_train_orginal, df_test_orginal = create_train_test(df_read, features,  \"2022-09-01\", 5)\n",
    "\n",
    "train_x_org, train_y_org, = df_to_xy(df_train_orginal, num_features, seq_length)\n",
    "test_x_org, test_y_org = df_to_xy(df_test_orginal, num_features, seq_length)\n",
    "\n",
    "train_x_scaled, test_x_scaled = min_max_scale(train_x_org, test_x_org)\n",
    "train_y_scaled, test_y_scaled = min_max_scale(train_y_org, test_y_org)\n",
    "\n",
    "train_x_scaled = np.reshape(train_x_scaled, (len(train_x_scaled), seq_length, num_features))\n",
    "test_x_scaled = np.reshape(test_x_scaled, (len(test_x_scaled), seq_length, num_features))\n",
    "\n",
    "print(f\"Train_x shape: {train_x_scaled.shape}, train_y shape: {train_y_scaled.shape}\")\n",
    "print(f\"Test_x shape: {test_x_scaled.shape}, test_y shape: {test_y_scaled.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Create sweep with ID: o19b188y\n",
      "Sweep URL: https://wandb.ai/avogadro/LSTM%20option%20pricing/sweeps/o19b188y\n"
     ]
    }
   ],
   "source": [
    "sweep_configuration = {\n",
    "    'method': 'random',\n",
    "    'name': 'sweep2',\n",
    "    'metric': {\n",
    "        'goal': 'minimize', \n",
    "        'name': 'loss'\n",
    "\t\t},\n",
    "    'parameters': {\n",
    "        \"units\": {'values': [75, 100, 200]},\n",
    "        \"dropout\": {'values': [0.05, 0.1, 0.2]},\n",
    "        \"recurrent_dropout\": {'values': [0.05, 0.1, 0.2]},\n",
    "        \"learning_rate\": {'values': [0.001, 0.01, 0.1]},\n",
    "        \"layers\": {'values': [3, 5, 8]},\n",
    "        \"seq_length\": {'values': [5, 10, 15]},\n",
    "        \"num_features\": {'values': [5, 10, 15]}\n",
    "     }\n",
    "}\n",
    "\n",
    "sweep_id = wandb.sweep(sweep=sweep_configuration, project=\"LSTM option pricing\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: \u001b[33mWARNING\u001b[0m Calling wandb.login() after wandb.init() has no effect.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 11tyspbl with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 3\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-9:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: jyg7fea2 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.001\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-10:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: fjzeau1z with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-11:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 8emv3ss8 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-12:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: foqerbqe with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-13:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 82npz2fi with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.001\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-14:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 0odz6f1a with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-15:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: x5qujf2l with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-16:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 2khd5aio with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-17:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: s25q8j1x with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-18:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: j58tkisi with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 3\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-19:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 1gijxgx5 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-20:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: csareq0m with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: fg7jiy6d with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 3\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.001\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-22:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: i2ybzekk with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-23:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: nhsczbf5 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 75\n",
      "Exception in thread Thread-24:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: ertpup4w with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.001\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-25:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 6k0z3be6 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-26:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: 8nqq6v3p with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 3\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-27:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: cfvbg8h2 with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 15\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-28:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Sweep Agent: Waiting for job.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Job received.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: cj46g7af with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.1\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 10\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 100\n",
      "Exception in thread Thread-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Agent Starting Run: lpub4hyo with config:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tdropout: 0.2\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlayers: 3\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tlearning_rate: 0.01\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tnum_features: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \trecurrent_dropout: 0.05\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tseq_length: 5\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \tunits: 200\n",
      "Exception in thread Thread-30:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 298, in _run_job\n",
      "    self._function()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 967, in __call__\n",
      "    inputs, args, kwargs = self._split_out_first_arg(args, kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 3011, in _split_out_first_arg\n",
      "    raise ValueError(\n",
      "ValueError: The first argument to `Layer.call` must always be passed.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/agents/pyagent.py\", line 303, in _run_job\n",
      "    wandb.finish(exit_code=1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 3621, in finish\n",
      "    wandb.run.finish(exit_code=exit_code, quiet=quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 292, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 255, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1739, in finish\n",
      "    return self._finish(exit_code, quiet)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 1745, in _finish\n",
      "    tel.feature.finish = True\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py\", line 40, in __exit__\n",
      "    self._run._telemetry_callback(self._obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 608, in _telemetry_callback\n",
      "    self._telemetry_flush()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/wandb_run.py\", line 619, in _telemetry_flush\n",
      "    self._backend.interface._publish_telemetry(self._telemetry_obj)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py\", line 97, in _publish_telemetry\n",
      "    self._publish(rec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py\", line 51, in _publish\n",
      "    self._sock_client.send_record_publish(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 221, in send_record_publish\n",
      "    self.send_server_request(server_req)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 155, in send_server_request\n",
      "    self._send_message(msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 152, in _send_message\n",
      "    self._sendall_with_error_handle(header + data)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py\", line 130, in _sendall_with_error_handle\n",
      "    sent = self._sock.send(data)\n",
      "BrokenPipeError: [Errno 32] Broken pipe\n"
     ]
    }
   ],
   "source": [
    "from keras.callbacks import EarlyStopping\n",
    "config_norm = {\n",
    "    \"units\": 100,\n",
    "    \"dropout\": 0.1,\n",
    "    \"recurrent_dropout\": 0.1,\n",
    "    \"learning_rate\": 0.001,\n",
    "    \"layers\": 5,\n",
    "    \"seq_length\": seq_length,\n",
    "    \"num_features\": num_features\n",
    "}\n",
    "\n",
    "def trainer(train_x, train_y, model):\n",
    "    epochs = 10\n",
    "    minibatch_size = 1024\n",
    "\n",
    "    early_stopping = EarlyStopping(\n",
    "        monitor='loss',\n",
    "        mode='min',\n",
    "        min_delta=1e-4,\n",
    "        patience=10,\n",
    "    )\n",
    "\n",
    "    model.fit(\n",
    "        train_x,\n",
    "        train_y,\n",
    "        batch_size = minibatch_size,\n",
    "        epochs = epochs,\n",
    "        callbacks = [early_stopping, WandbCallback()]\n",
    "    )\n",
    "\n",
    "model = create_model(config_norm)\n",
    "\n",
    "wandb.agent(sweep_id=sweep_id, function=model)\n",
    "\n",
    "trainer(train_x_scaled, train_y_scaled, model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 121672 entries, 1395271 to 1533711\n",
      "Data columns (total 34 columns):\n",
      " #   Column           Non-Null Count   Dtype         \n",
      "---  ------           --------------   -----         \n",
      " 0   Quote_date       121672 non-null  datetime64[ns]\n",
      " 1   Expire_date      121672 non-null  datetime64[ns]\n",
      " 2   Underlying_last  121672 non-null  float64       \n",
      " 3   Strike           121672 non-null  float64       \n",
      " 4   Moneyness        121672 non-null  float64       \n",
      " 5   Ask              121672 non-null  float64       \n",
      " 6   Bid              121672 non-null  float64       \n",
      " 7   Ttl              121672 non-null  int64         \n",
      " 8   Volatility       121672 non-null  float64       \n",
      " 9   R                121672 non-null  float64       \n",
      " 10  Moneyness-4      121672 non-null  float64       \n",
      " 11  Ttl-4            121672 non-null  float64       \n",
      " 12  R-4              121672 non-null  float64       \n",
      " 13  Volatility-4     121672 non-null  float64       \n",
      " 14  Moneyness-3      121672 non-null  float64       \n",
      " 15  Ttl-3            121672 non-null  float64       \n",
      " 16  R-3              121672 non-null  float64       \n",
      " 17  Volatility-3     121672 non-null  float64       \n",
      " 18  Moneyness-2      121672 non-null  float64       \n",
      " 19  Ttl-2            121672 non-null  float64       \n",
      " 20  R-2              121672 non-null  float64       \n",
      " 21  Volatility-2     121672 non-null  float64       \n",
      " 22  Moneyness-1      121672 non-null  float64       \n",
      " 23  Ttl-1            121672 non-null  float64       \n",
      " 24  R-1              121672 non-null  float64       \n",
      " 25  Volatility-1     121672 non-null  float64       \n",
      " 26  Moneyness-0      121672 non-null  float64       \n",
      " 27  Ttl-0            121672 non-null  int64         \n",
      " 28  R-0              121672 non-null  float64       \n",
      " 29  Volatility-0     121672 non-null  float64       \n",
      " 30  Bid_last         121672 non-null  float64       \n",
      " 31  Ask_last         121672 non-null  float64       \n",
      " 32  Prediction_bid   121672 non-null  float32       \n",
      " 33  Prediction_ask   121672 non-null  float32       \n",
      "dtypes: datetime64[ns](2), float32(2), float64(28), int64(2)\n",
      "memory usage: 31.6 MB\n",
      "        Quote_date Expire_date  Underlying_last  Strike  Moneyness     Ask  \\\n",
      "1395271 2022-09-08  2022-09-09          4005.86  1000.0   4.005860  3004.8   \n",
      "1395272 2022-09-08  2022-09-09          4005.86  1200.0   3.338217  2804.8   \n",
      "1395273 2022-09-08  2022-09-09          4005.86  1400.0   2.861329  2604.6   \n",
      "1395274 2022-09-08  2022-09-09          4005.86  1600.0   2.503662  2405.4   \n",
      "1395275 2022-09-08  2022-09-09          4005.86  1800.0   2.225478  2205.4   \n",
      "\n",
      "            Bid  Ttl  Volatility     R  ...   R-1  Volatility-1  Moneyness-0  \\\n",
      "1395271  2997.2    1    0.247916  3.06  ...  3.07      0.247855     4.005860   \n",
      "1395272  2797.3    1    0.247916  3.06  ...  3.07      0.247855     3.338217   \n",
      "1395273  2597.1    1    0.247916  3.06  ...  3.07      0.247855     2.861329   \n",
      "1395274  2397.1    1    0.247916  3.06  ...  3.07      0.247855     2.503662   \n",
      "1395275  2197.6    1    0.247916  3.06  ...  3.07      0.247855     2.225478   \n",
      "\n",
      "         Ttl-0   R-0  Volatility-0  Bid_last  Ask_last  Prediction_bid  \\\n",
      "1395271      1  3.06      0.247916    2997.2    3004.8     2958.293945   \n",
      "1395272      1  3.06      0.247916    2797.3    2804.8     2743.209229   \n",
      "1395273      1  3.06      0.247916    2597.1    2604.6     2525.886963   \n",
      "1395274      1  3.06      0.247916    2397.1    2405.4     2305.510254   \n",
      "1395275      1  3.06      0.247916    2197.6    2205.4     2084.317627   \n",
      "\n",
      "         Prediction_ask  \n",
      "1395271     2938.088623  \n",
      "1395272     2720.194580  \n",
      "1395273     2500.249023  \n",
      "1395274     2278.655273  \n",
      "1395275     2057.875977  \n",
      "\n",
      "[5 rows x 34 columns]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.preprocessing import MinMaxScaler\n",
    "def prediction(df_test, test_x, model, train_y_org):\n",
    "    predictions = np.array(model(test_x))\n",
    "    scaler = MinMaxScaler().fit(train_y_org)\n",
    "    predictions = scaler.inverse_transform(predictions)\n",
    "    bid, ask = predictions[:, :1], predictions[:, 1:]\n",
    "    df_test[\"Prediction_bid\"] = bid\n",
    "    df_test[\"Prediction_ask\"] = ask\n",
    "    return df_test\n",
    "\n",
    "df_test = prediction(df_test_orginal, test_x_scaled, model, train_y_org)\n",
    "\n",
    "df_test.info()\n",
    "print(df_test.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "            Bid     Ask  Prediction_bid  Prediction_ask\n",
      "1395271  2997.2  3004.8     2958.293945     2938.088623\n",
      "1395272  2797.3  2804.8     2743.209229     2720.194580\n",
      "1395273  2597.1  2604.6     2525.886963     2500.249023\n",
      "1395274  2397.1  2405.4     2305.510254     2278.655273\n",
      "1395275  2197.6  2205.4     2084.317627     2057.875977\n",
      "1395276  1998.1  2004.9     1864.251953     1839.673096\n",
      "1395277  1797.7  1805.5     1644.697632     1623.189331\n",
      "1395278  1597.5  1605.0     1422.385498     1404.850708\n",
      "1395279  1397.3  1405.0     1193.704590     1180.607300\n",
      "1395280  1297.3  1305.0     1076.631226     1065.778442\n",
      "1395281  1197.3  1204.8      958.215576      949.564575\n",
      "1395282  1150.9  1155.4      898.755554      891.181519\n",
      "1395283  1100.9  1105.4      839.310547      832.795837\n",
      "1395284  1051.0  1055.4      780.044556      774.571716\n",
      "1395285  1000.4  1005.4      721.139832      716.691528\n",
      "1395286   950.4   955.4      662.790710      659.352112\n",
      "1395287   900.4   906.1      605.201416      602.758606\n",
      "1395288   850.4   856.1      548.577576      547.119385\n",
      "1395289   801.0   806.1      493.122681      492.639526\n",
      "1395291   751.0   755.5      439.030334      439.514282\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 121672 entries, 1395271 to 1533711\n",
      "Data columns (total 34 columns):\n",
      " #   Column           Non-Null Count   Dtype         \n",
      "---  ------           --------------   -----         \n",
      " 0   Quote_date       121672 non-null  datetime64[ns]\n",
      " 1   Expire_date      121672 non-null  datetime64[ns]\n",
      " 2   Underlying_last  121672 non-null  float64       \n",
      " 3   Strike           121672 non-null  float64       \n",
      " 4   Moneyness        121672 non-null  float64       \n",
      " 5   Ask              121672 non-null  float64       \n",
      " 6   Bid              121672 non-null  float64       \n",
      " 7   Ttl              121672 non-null  int64         \n",
      " 8   Volatility       121672 non-null  float64       \n",
      " 9   R                121672 non-null  float64       \n",
      " 10  Moneyness-4      121672 non-null  float64       \n",
      " 11  Ttl-4            121672 non-null  float64       \n",
      " 12  R-4              121672 non-null  float64       \n",
      " 13  Volatility-4     121672 non-null  float64       \n",
      " 14  Moneyness-3      121672 non-null  float64       \n",
      " 15  Ttl-3            121672 non-null  float64       \n",
      " 16  R-3              121672 non-null  float64       \n",
      " 17  Volatility-3     121672 non-null  float64       \n",
      " 18  Moneyness-2      121672 non-null  float64       \n",
      " 19  Ttl-2            121672 non-null  float64       \n",
      " 20  R-2              121672 non-null  float64       \n",
      " 21  Volatility-2     121672 non-null  float64       \n",
      " 22  Moneyness-1      121672 non-null  float64       \n",
      " 23  Ttl-1            121672 non-null  float64       \n",
      " 24  R-1              121672 non-null  float64       \n",
      " 25  Volatility-1     121672 non-null  float64       \n",
      " 26  Moneyness-0      121672 non-null  float64       \n",
      " 27  Ttl-0            121672 non-null  int64         \n",
      " 28  R-0              121672 non-null  float64       \n",
      " 29  Volatility-0     121672 non-null  float64       \n",
      " 30  Bid_last         121672 non-null  float64       \n",
      " 31  Ask_last         121672 non-null  float64       \n",
      " 32  Prediction_bid   121672 non-null  float32       \n",
      " 33  Prediction_ask   121672 non-null  float32       \n",
      "dtypes: datetime64[ns](2), float32(2), float64(28), int64(2)\n",
      "memory usage: 31.6 MB\n"
     ]
    }
   ],
   "source": [
    "print(df_test.head(20)[[\"Bid\", \"Ask\", \"Prediction_bid\", \"Prediction_ask\"]])\n",
    "df_test.info()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.1 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.1"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
